NAME: flow_lvm_lr1e-4_no_pe
BASE_PACKAGE: normflows # nflows

DATASETS:
  PATH: /data/net/userstore/qf/hithand_data/data/ffhnet-data # /data/hdd1/qf/hithand_data/ffhnet-data
  GAZEBO_OBJ_PATH:  /data/net/userstore/qf/hithand_data/data/gazebo-objects # /home/Dyb/Projects/gazebo-objects
  GRASP_DATA_NANE: grasp_data_all.h5
  POSITIVE_ONLY: True
  NEGATIVE_ONLY: False
  POS_AND_NEG_GRASP: False

GENERAL:
  TOTAL_STEPS: 200000 # 200000, 300000 #100000 for train with nll and second 100000 for fintune
  LOG_STEPS: 1000
  VAL_STEPS: 1000
  # CHECKPOINT_STEPS: 100
  NUM_WORKERS: 8

TRAIN:
  OPT: AdamW # SGD, AdamW
  LR: 1e-4
  WARM_UP_STEPS: 0
  WEIGHT_DECAY: 0.0005 # 0.0005
  BATCH_SIZE: 64
  LOSS_REDUCTION: mean
  NUM_TRAIN_SAMPLES: 1
  NUM_TEST_SAMPLES: 1
  BETA1: 0.9

LOSS_WEIGHTS:
  C: -1e4  # truncate value for loss_neg_nll
  ORTHOGONAL: 0.1
  KL_LOSS_WEIGHT_START: 1e-7
  KL_LOSS_WEIGHT_END: 0.1
  NLL: 1
  KL_NLL: 1
  KL_ENT: 1
  NLL_POS: 1
  NLL_NEG: 1
  ROT: 0.1 # TODO: to be tuned
  TRANSL: 0.1 # In FFHNet, transl coef is 100x of rot coef

MODEL:
  BACKBONE:
    # posterior distribution: True -> Gaussian; False -> delta;
    PROBABILISTIC: True
    # PCD encoder
    PCD_ENC_HIDDEN_DIM: 128
    # Grasp encoder
    GRASP_ENC: None
    GRASP_ENC_PE: False
    GRASP_ENC_HIDDEN_DIM: 64
    # PRIOR FLOW related
    PRIOR_FLOW: True
    PRIOR_FLOW_COND: True
    PRIOR_FLOW_BASE: "gaussian" # gmm, gaussian, cond_gaussian, cond_rsb
    PRIOR_FLOW_NUM_LAYERS: 8 # numbers of flow layers about [Actnorm, LULinear, Coupling]
    PRIOR_FLOW_LAYER_HIDDEN_FEATURES: 512
    PRIOR_FLOW_LAYER_DEPTH: 4 # number of resblock in resnet
  FLOW:
    BASE: "cond_gaussian" # gmm, gaussian, cond_gaussian, cond_rsb
    # RSB related
    RSB_EPS: 0.01
    RSB_T: 100 
    RSB_ACC_HIDDEN: 128
    RSB_ACC_LAYES: 3
    # GMM related
    GMM_MODE: 1
    GMM_TRAINABLE: True
    # DIM should be 136 for normflow package (split requires even number)
    # DIM is 135 for nflows pacakge.
    DIM: 22 # input dims, 136ï¼š positional encoding; 22(3+3+16): no position encoding
    CONTEXT_FEATURES: 128 # features dim from backbone (TODO: try context_features same dim as DIM)
    NUM_LAYERS: 8 # numbers of layers about [Actnorm, LULinear, Coupling]
    LAYER_HIDDEN_FEATURES: 512 #1024 # hidden layer dims in resnet inside Glow
    LAYER_DEPTH: 4 # number of resblock in resnet

EXTRA:
  FOCAL_LENGTH: 5000
